php_role:
  common:
    packages:
      - php-common
      - php-cli
      - php-intl
      - php-curl
      - php-mysqlnd
      - php-gd
      - php-pear
      - php-opcache
      - php-mbstring
      - php-xml
      - php-pecl-apcu
      - php-pecl-imagick
      - php-json
      - php-pecl-zip
      - php-readline
      - php-soap
